yp/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from datetime import datetime

from yp import db
from yp.forms import UserCreateForm, UserInfoForm, UserLoginForm
from yp.models import tb_user, tb_user_info

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = tb_user.query.filter_by(user_email=form.email.data).first()
        if not email:
            user = tb_user(user_name=form.username.data,
                        user_pw=generate_password_hash(form.password1.data),
                        user_email=form.email.data,
                        user_status=1)
            db.session.add(user)
            db.session.commit()

            session.clear()
            session['user'] = user.user_email
            return redirect(url_for('auth.more_info'))
        else:
            flash('이미 존재하는 이메일입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/more_info/', methods=('GET', 'POST'))
def more_info():
    form = UserInfoForm()
    today = datetime.now().date()
    if request.method == 'POST' and form.validate_on_submit():
        user = tb_user_info(user_email=session['user'],
                            user_weight=int(form.user_weight.data),
                            user_height=int(form.user_height.data),
                            user_birth=form.user_birth.data,
                            user_cal=form.user_cal.data,
                            user_goal=int(form.user_goal.data),
                            user_sex=form.user_sex.data,
                            user_pa=form.user_pa.data
                            )

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.main'))
    return render_template('auth/more_info.html', form=form, today=today)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = tb_user.query.filter_by(user_email=form.email.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.user_pw, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        elif user.user_email == "miso324@naver.com":
            session.clear()
            session['user'] = user.user_email
            return redirect(url_for('admin.admin'))
        elif error is None:
            session.clear()
            session['user'] = user.user_email
            return redirect(url_for('main.main'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_email = session.get('user')
    if user_email is None:
        g.user = None
        g.user_info = None
    else:
        g.user = tb_user.query.get(user_email)
        g.user_info = tb_user_info.query.get(user_email)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.main'))


@bp.route('/signout/', methods=('GET', 'POST'))
def signout():
    if g.user:
        if request.method == 'POST':
            user = db.session.query(tb_user).filter_by(user_email=g.user.user_email).first()
            db.session.delete(user)
            db.session.commit()
            session.clear()
            return render_template('main.html')
        return render_template('auth/signout.html', login = True)
    else:
        return render_template("error.html", login = True)

# @bp.route('/mypage/', methods=('GET', 'POST'))
# def mypage():
#     form = UserInfoForm()
#     return render_template("auth/mypage.html", login = True)

# @bp.route('/mypage/', methods=('GET', 'POST'))
# def mypage():
#     form = UserInfoForm()
#     if g.user:
#         if request.method == 'POST':
#             user = db.session.query(tb_user).filter_by(user_email=g.user.user_email).first()
            
#             db.session.commit()
            
#             return render_template("auth/mypage.html", login = True)
#         return render_template("auth/mypage.html", login = True)
#     else:
#         return render_template("error.html")

    # # form = UserInfoForm()
    # user_email = session.get('user')
    # user_weight_edit = db.session.query(tb_user).filter_by(user_email=g.user.user_email).user_weight()
    # user_height = db.session.query(tb_user).filter_by(user_email=g.user.user_email).user_height()
    # user_birth = db.session.query(tb_user).filter_by(user_email=g.user.user_email).user_birth()
    # user_cal = db.session.query(tb_user).filter_by(user_email=g.user.user_email).user_cal()
    # user_goal = db.session.query(tb_user).filter_by(user_email=g.user.user_email).user_goal()
    # user_sex = db.session.query(tb_user).filter_by(user_email=g.user.user_email).user_sex()
    # user_pa = db.session.query(tb_user).filter_by(user_email=g.user.user_email).user_pa()

    # db.session.commit()
    # return render_template("auth/mypage.html", login = True)

# @bp.route('/mypage/', methods=('GET', 'POST'))
# def mypage():
#     form = UserInfoForm()
#     if request.method == 'GET':
#         user = tb_user_info(user_email=session['user'],
#                             user_weight=int(form.user_weight.data),
#                             user_height=int(form.user_height.data),
#                             user_birth=form.user_birth.data,
#                             user_cal=form.user_cal.data,
#                             user_goal=int(form.user_goal.data),
#                             user_sex=form.user_sex.data,
#                             user_pa=form.user_pa.data
#                             )

#         db.session.commit()
#         return redirect(url_for('main.main'))
#     return render_template("auth/mypage.html", form=form, login = True)

yp/views/main_views.py
from flask import Blueprint, render_template, session
from yp.models import tb_user

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def main():
   if 'user' in session:
      user_email = session.get("user")
      user = tb_user.query.filter_by(user_email=user_email).first()
      return render_template("main.html", username = user.user_name, login = True)
   else:
      return render_template("main.html", login = False)

@bp.route("/aboutus")
def aboutus():
   if 'user' in session:
      user_email = session.get("user")
      user = tb_user.query.filter_by(user_email=user_email).first()
      return render_template("aboutus.html", username = user.user_name, login = True)
   else:
      return render_template("aboutus.html", login = False)

@bp.route("/error")
def error():
   if 'user' in session:
      user_email = session.get("user")
      user = tb_user.query.filter_by(user_email=user_email).first()
      return render_template("error.html", username = user.user_name, login = True)
   else:
      return render_template("error.html", login = False)

yp/views/upload_views.py
from flask import Blueprint, render_template, request, g
from yp.models import tb_user_img, tb_food_img
from yp import db
from sqlalchemy import func, and_
from functions import func_ml, func_user__nutrient
from yp.views.auth_views import session
from yp.models import tb_user

import config
import os


bp = Blueprint('upload', __name__, url_prefix='/upload')
NEW_IMG = None


@bp.route('/')
def upload():
    # if 'user' in session:
    #   user_email = session.get("user")
    #   user = tb_user.query.filter_by(user_email=user_email).first()
    #   return render_template("upload/upload.html", username = user.user_name, login = True)
    # else:
    #   return render_template("upload/upload.html", login = False)

    return render_template("upload/upload.html", login = True)

@bp.route("/", methods=["GET","POST"])
def upload_done():
    try:
        global NEW_IMG
        NEW_IMG = tb_user_img()
        NEW_IMG.upload_index = db.session.query(func.count(tb_user_img.upload_index)).all()[0][0] + 1
        NEW_IMG.upload_user = 'geehyun'
        NEW_IMG.upload_location = os.path.join(config.BASE_DIR, f"yp/static/img/user_upload/{NEW_IMG.upload_index}.jpg")

        uploaded_files = request.files["food_img"]
        uploaded_files.save(NEW_IMG.upload_location)

        # DS 결과
        global model_result
        model_result = func_ml.image_prediction_result(NEW_IMG.upload_location, './', 'DenseNet201_129menu.h5')

        return render_template("upload/upload_check.html", first = model_result["TOP1"], photo = f"img/user_upload/{NEW_IMG.upload_index}.jpg", login = True)
    
    except:
        return render_template("error_submit.html", login = True)

@bp.route("/re", methods=["GET","POST"])
def double_check():
    if NEW_IMG:
        return render_template("upload/upload_check2.html", food_list = model_result["TOP2to5"], photo = f"img/user_upload/{NEW_IMG.upload_index}.jpg", login = True)
        
    else:
        return render_template("error.html", login = True)


@bp.route("/how", methods=["GET","POST"])
def how():
    if NEW_IMG:
        NEW_IMG.upload_foodname = request.form["food_name"].replace(" ", "")

        # 이미 가지고 있는 음식 목록에 있다면
        food_being = tb_food_img.query.filter_by(food_name=NEW_IMG.upload_foodname).first()
        if food_being:
            NEW_IMG.upload_isnew = False
            db.session.add(NEW_IMG)
            db.session.commit()
            return render_template("upload/upload_how.html", photo = f"img/user_upload/{NEW_IMG.upload_index}.jpg", login = True)
        else:
            NEW_IMG.upload_isnew = True
            db.session.add(NEW_IMG)
            db.session.commit()
            return render_template("upload/upload_isnew.html", login = True)

    else:
        return render_template("error.html", login = True)

@bp.route("/result", methods=["POST"])
def result():
    food_being = tb_food_img.query.filter_by(food_name=NEW_IMG.upload_foodname).first()

    RATIO = float(request.form["ratio"])

    # 사용자
    user_age = func_user__nutrient.user_age(g.user_info.user_birth, )
    weight_s = func_user__nutrient.standard_weight(g.user_info.user_sex, g.user_info.user_height)
    weight_a = func_user__nutrient.adjusted_weight(g.user_info.user_weight, weight_s)
    user_calorie = func_user__nutrient.calorie_counting(g.user_info.user_sex, user_age, g.user_info.user_height, weight_a, str(g.user_info.user_pa))
    user_nutrient_dic = func_user__nutrient.necessary_nutrients(g.user_info.user_sex, user_age, g.user_info.user_weight, user_calorie)

    remain_dict = {}
    overdose = []
    for nutrient in user_nutrient_dic:
        remain_dict[nutrient] = max(user_nutrient_dic[nutrient] - food_being[nutrient] * RATIO, 0)
        if remain_dict[nutrient] == 0:
            overdose.append(nutrient)
        
    text = f"오늘 {', '.join(list(map(lambda en: func_user__nutrient.en_ko_dict[en], overdose)))}(을)를 너무 많이 섭취했어요!"

    res_list = db.session.query(tb_food_img).filter(and_(tb_food_img.vitamin_A <= remain_dict['vitamin_A'],
                                                        tb_food_img.vitamin_D <= remain_dict['vitamin_D'],
                                                        tb_food_img.vitamin_E <= remain_dict['vitamin_E'],
                                                        tb_food_img.calcium <= remain_dict['calcium'],
                                                        tb_food_img.iron <= remain_dict['iron'],
                                                        tb_food_img.magnesium <= remain_dict['magnesium'],
                                                        tb_food_img.phosphorus <= remain_dict['phosphorus'],
                                                        tb_food_img.potassium <= remain_dict['potassium'],
                                                        tb_food_img.sodium <= remain_dict['sodium'],
                                                        tb_food_img.zinc <= remain_dict['zinc'],
                                                        tb_food_img.copper <= remain_dict['copper']
                                                        )
                                                    ).all()

    return render_template("upload/upload_result.html", text=text, res_list=res_list, login = True)

yp/templates/aboutus.html
{% extends "main.html" %}
{% block title %}Index{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<body>
    <div style="text-align: center;">
        <h5 style="padding-bottom: 10px;">우리는! 스무디킹!</h5>
        <h5 style="padding-bottom: 10px;">팀장 : 이지현</h5>
        <h5 style="padding-bottom: 10px;">DS : 한현구, 손다영</h5>
        <h5 style="padding-bottom: 10px;">DA : 심철우, 김재성</h5>
        <h5 style="padding-bottom: 10px;">DE : 이지현, 박상현</h5>
        <h5 style="padding-bottom: 20px;">Yam-Pick 프로젝트 고생 많았습니다.</h5>
        <p>
            <form action="{{ url_for('main.main') }}">
                <input type="submit" value = "이동">
            </form>
        </p>
    </div>
</body>
{% endblock %}
</html>

yp/templates/error.html
{% extends "main.html" %}
{% block title %}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<body>
    <div style="text-align: center;">
        <h5 style="padding-bottom: 20px;">잘못된 접근입니다.</h5>
        <p>
            <form action="{{ url_for('main.main') }}">
                <input type="submit" name = "home" value = "이동" >
            </form>
        </p>
    </div>
</body>
{% endblock %}
</html>

yp/templates/error_submit.html
{% extends "main.html" %}
{% block title %}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<body>
    <div style="text-align: center;">
        <h5 style="padding-bottom: 10px;">잘못된 접근입니다.</h5>
        <h5 style="padding-bottom: 10px;">이미지 파일에 문제가 있거나 파일이 첨부되지 않았습니다.</h5>
        <h5 style="padding-bottom: 20px;">새로운 이미지 파일을 첨부하거나 파일을 첨부하여 제출해 주십시오.</h5>
        <p>
            <form action="{{ url_for('upload.upload') }}">
                <input type="submit" value = "이동">
            </form>
        </p>
    </div>
</body>
{% endblock %}
</html>

yp/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

yp/templates/leave.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    정말 탈퇴하시겠습니까? [네] [아니오]
    <!-- 메인 화면으로 이동 -->
</body>
</html>

yp/templates/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    테스트 성공!
</body>
</html>

yp/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/headers/">

    <title>{% block title %}{% endblock %} Yam-Pick</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
    <!-- Bootstrap core CSS -->
<link href="/static/css/bootstrap.min.css" rel="stylesheet">

     <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
     </style>
  
      
      <!-- Custom styles for this template -->
    <!-- <link href="static/css/headers.css" rel="stylesheet"> -->
    {% endblock %}
</head>
<body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        
        {% if login ==True %}
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" style="text-align: center;margin: 10px 0px;">
            <img src="/static/img/Yam-Pick_logo_main.jpg" alt="" width="50" height="50" >
          </a></li>
          <li><a href="/" class="nav-link px-2 text-secondary" style="font-size: 1.3em; text-align: center;">Yam-Pick</a></li>
          <li><a href="/upload" class="nav-link px-2 text-white" style="margin:5px 0px;">업로드</a></li>
          <!-- <li><a href="/data" class="nav-link px-2 text-white">데이터</a></li> -->
          <li><a href="/aboutus" class="nav-link px-2 text-white" style="margin:5px 0px;">만든이들</a></li>
          <!-- <li><a href="/error" class="nav-link px-2 text-white" style="margin:5px 0px;">에러</a></li> -->
          <!-- <li><a href="/auth/mypage" class="nav-link px-2 text-white">회원정보 수정</a></li> -->
        </ul>
        
        <div class="text-end">
          <a href ="{{ url_for('auth.logout') }}">
          <button type="button" class="btn btn-outline-light me-2">로그아웃</button>
          </a>
          <a href ="/auth/signout">
          <button type="button" class="btn btn-warning">회원탈퇴</button>
          </a>
        </div>
        {% else %}
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" style="text-align: center; margin-right: 10px;">
            <img src="/static/img/Yam-Pick_logo_main.jpg" alt="" width="50" height="50">
          </a></li>
          <li><a href="/" class="nav-link px-2 text-secondary" style="font-size: 1.3em; text-align: center;">Yam-Pick</a></li>
          <li><a href="/aboutus" class="nav-link px-2 text-white" style="margin:5px 0px;">만든이들</a></li>
        </ul>

        <div class="text-end">
          <a href ="/auth/login">
          <button type="button" class="btn btn-outline-light me-2">로그인</button>
          </a>
          <a href ="/auth/signup">
          <button type="button" class="btn btn-warning">회원가입</button>
          </a>
        </div>
        {% endif %}
      </div>
    </div>
  </header>
  
  <div class="container col-xxl-8 px-4 py-5">{% block content %}
      <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <div class="col-10 col-sm-8 col-lg-6">
          <img src="/static/img/main_background.jpg" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
        </div>
        <div class="col-lg-6">
          <h1 class="display-5 fw-bold lh-1 mb-3">한식의 놀라운 비밀 알고 계신가요?</h1>
          <p class="lead">
              한식의 영양 성분을 분석한 결과를 제공하여 다이어트의 본래의 의미를 되찾고자 합니다.<br>
              다이어트 식단관리에 필요한 복잡한 영양성분을 계산, 기록, 분석하여 제공하고 합니다.<br>
              사용자가 건강하게 다이어트 목표를 달성 할 수 있도록 지원하는 서비스입니다.
          </p>
          <div class="d-grid gap-2 d-md-flex justify-content-md-start">
            
            {% if login ==True %}
            <a href ="/upload">
              <button type="button" class="btn btn-primary btn-lg px-4 me-md-2">업로드</button>
            </a>
            
            {% else %}
            
            {% endif %}
          </div>
        </div>
      {% endblock %}
      </div>
  </div>

  <div class="container"> {% block footer %}
      <footer class="py-3 my-4">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Yam-Pick</a></li>
          <li class="nav-item"><a href="/aboutus" class="nav-link px-2 text-muted">만든이들</a></li>
          <!-- <li class="nav-item"><a href="/auth/login" class="nav-link px-2 text-muted">더 알아보기</a></li> -->
          </ul>
          <p class="text-center text-muted">&copy; 2022 Yam-Pick, Inc</p>
      </footer>
      {% endblock %}
  </div>

</body>
</html>

yp/templates/upload_check.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
    	<img src = {{url_for("static", filename = photo)}}>
    </div>
    이 음식은 {{first}}(이)가 맞나요?
    <p>
        <form action="{{ url_for('upload.how') }}" method = "post">
            <input type="submit" name = "food_name" value = "{{ first }}" >
        </form>
    </p>
    <p>
        <a href ="{{ url_for('upload.double_check') }}">아니요</a>
    </p>
</body>
</html>

yp/templates/upload_check2.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
    	<img src = {{url_for("static", filename = photo)}}>
    </div>
    <div>
    <form action="{{ url_for('upload.how') }}" method = "post">
        {% for food in food_list %}
        <input type="submit" value = "{{ food }}" name = "food_name">
        {% endfor %}
    </form>
    <form action="{{ url_for('upload.how') }}" method = "post">
        <input placeholder="직접 입력하기" name = "food_name">
        <button type="submit">next</button>
    </form>
    </div>
</body>
</html>

yp/templates/upload_how.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
    	<img src = {{url_for("static", filename = photo)}}>
    </div>
    <form action="{{ url_for('upload.result') }}" method = "post">
        <input type="submit" value = 0.2 name = "ratio">
        <input type="submit" value = 0.4 name = "ratio">
        <input type="submit" value = 0.6 name = "ratio">
        <input type="submit" value = 0.8 name = "ratio">
        <input type="submit" value = 1 name = "ratio">
    </form>
</body>
</html>