yp/views/main_views.py
from flask import Blueprint, render_template, session
from yp.models import tb_user

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def main():
   if 'user' in session:
      user_email = session.get("user")
      user = tb_user.query.filter_by(user_email=user_email).first()
      return render_template("main.html", username = user.user_name, login = True)
   else:
      return render_template("main.html", login = False)

@bp.route("/aboutus")
def aboutus():
   if 'user' in session:
      user_email = session.get("user")
      user = tb_user.query.filter_by(user_email=user_email).first()
      return render_template("aboutus.html", username = user.user_name, login = True)
   else:
      return render_template("aboutus.html", login = False)

@bp.route("/error")
def error():
   if 'user' in session:
      user_email = session.get("user")
      user = tb_user.query.filter_by(user_email=user_email).first()
      return render_template("error.html", username = user.user_name, login = True)
   else:
      return render_template("error.html", login = False)

yp/views/upload_views.py
from flask import Blueprint, render_template, request, g
from yp.models import tb_user_img, tb_food_img
from yp import db
from sqlalchemy import func, and_
from functions import func_ml, func_user__nutrient
from yp.views.auth_views import session
from yp.models import tb_user

import config
import os


bp = Blueprint('upload', __name__, url_prefix='/upload')
NEW_IMG = None


@bp.route('/')
def upload():
    # if 'user' in session:
    #   user_email = session.get("user")
    #   user = tb_user.query.filter_by(user_email=user_email).first()
    #   return render_template("upload/upload.html", username = user.user_name, login = True)
    # else:
    #   return render_template("upload/upload.html", login = False)

    return render_template("upload/upload.html", login = True)

@bp.route("/", methods=["GET","POST"])
def upload_done():
    try:
        global NEW_IMG
        NEW_IMG = tb_user_img()
        NEW_IMG.upload_index = db.session.query(func.count(tb_user_img.upload_index)).all()[0][0] + 1
        NEW_IMG.upload_user = 'geehyun'
        NEW_IMG.upload_location = os.path.join(config.BASE_DIR, f"yp/static/img/user_upload/{NEW_IMG.upload_index}.jpg")

        uploaded_files = request.files["food_img"]
        uploaded_files.save(NEW_IMG.upload_location)

        # DS 결과
        global model_result
        model_result = func_ml.image_prediction_result(NEW_IMG.upload_location, './', 'DenseNet201_129menu.h5')

        return render_template("upload/upload_check.html", first = model_result["TOP1"], photo = f"img/user_upload/{NEW_IMG.upload_index}.jpg", login = True)
    
    except:
        return render_template("error_submit.html", login = True)

@bp.route("/re", methods=["GET","POST"])
def double_check():
    if NEW_IMG:
        return render_template("upload/upload_check2.html", food_list = model_result["TOP2to5"], photo = f"img/user_upload/{NEW_IMG.upload_index}.jpg", login = True)
        
    else:
        return render_template("error.html", login = True)


@bp.route("/how", methods=["GET","POST"])
def how():
    if NEW_IMG:
        NEW_IMG.upload_foodname = request.form["food_name"].replace(" ", "")

        # 이미 가지고 있는 음식 목록에 있다면
        food_being = tb_food_img.query.filter_by(food_name=NEW_IMG.upload_foodname).first()
        if food_being:
            NEW_IMG.upload_isnew = False
            db.session.add(NEW_IMG)
            db.session.commit()
            return render_template("upload/upload_how.html", photo = f"img/user_upload/{NEW_IMG.upload_index}.jpg", login = True)
        else:
            NEW_IMG.upload_isnew = True
            db.session.add(NEW_IMG)
            db.session.commit()
            return render_template("upload/upload_isnew.html", login = True)

    else:
        return render_template("error.html", login = True)

@bp.route("/result", methods=["POST"])
def result():
    food_being = tb_food_img.query.filter_by(food_name=NEW_IMG.upload_foodname).first()

    RATIO = float(request.form["ratio"])

    # 사용자
    user_age = func_user__nutrient.user_age(g.user_info.user_birth, )
    weight_s = func_user__nutrient.standard_weight(g.user_info.user_sex, g.user_info.user_height)
    weight_a = func_user__nutrient.adjusted_weight(g.user_info.user_weight, weight_s)
    user_calorie = func_user__nutrient.calorie_counting(g.user_info.user_sex, user_age, g.user_info.user_height, weight_a, str(g.user_info.user_pa))
    user_nutrient_dic = func_user__nutrient.necessary_nutrients(g.user_info.user_sex, user_age, g.user_info.user_weight, user_calorie)

    remain_dict = {}
    overdose = []
    for nutrient in user_nutrient_dic:
        remain_dict[nutrient] = max(user_nutrient_dic[nutrient] - food_being[nutrient] * RATIO, 0)
        if remain_dict[nutrient] == 0:
            overdose.append(nutrient)
        
    text = f"오늘 {', '.join(list(map(lambda en: func_user__nutrient.en_ko_dict[en], overdose)))}(을)를 너무 많이 섭취했어요!"

    res_list = db.session.query(tb_food_img).filter(and_(tb_food_img.vitamin_A <= remain_dict['vitamin_A'],
                                                        tb_food_img.vitamin_D <= remain_dict['vitamin_D'],
                                                        tb_food_img.vitamin_E <= remain_dict['vitamin_E'],
                                                        tb_food_img.calcium <= remain_dict['calcium'],
                                                        tb_food_img.iron <= remain_dict['iron'],
                                                        tb_food_img.magnesium <= remain_dict['magnesium'],
                                                        tb_food_img.phosphorus <= remain_dict['phosphorus'],
                                                        tb_food_img.potassium <= remain_dict['potassium'],
                                                        tb_food_img.sodium <= remain_dict['sodium'],
                                                        tb_food_img.zinc <= remain_dict['zinc'],
                                                        tb_food_img.copper <= remain_dict['copper']
                                                        )
                                                    ).all()

    return render_template("upload/upload_result.html", text=text, res_list=res_list, login = True)

yp/templates/upload/upload.html
{% extends "main.html" %}
{% block title %}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<body>
    <div style="text-align:center;">
        <h5 style="padding-bottom: 20px;">
            밝은 곳에서 사진이 가운데 오도록 촬영 후 업로드 해주세요!
        </h5>
        <p>
            <form method="POST" enctype="multipart/form-data" action="{{ url_for('upload.upload') }}">
                <input type="file" name="food_img">
                <input type="submit" value = "제출">
            </form>
        </p>
    </div>
</body>
{% endblock %}
</html>

yp/templates/upload/upload_check.html
{% extends "main.html" %}
{% block title %}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<body>
    <div style="text-align:center;">
        <div style="padding-bottom: 10px;">
            <img src = {{url_for("static", filename = photo)}}>
        </div>
        <h5 style="padding-bottom: 10px;">이 음식이 {{first}}(이)가 맞나요? 그러면 아래 버튼을 눌러주세요!</h5>
        <p>
            <form action="{{ url_for('upload.how') }}" method = "post" style="padding-bottom: 10px;">
                <input type="submit" name = "food_name" value="{{first}}">
            </form>
        </p>
        <h5 style="padding-bottom: 10px;"> 다른 음식이면 아래 버튼을 눌러주세요!</h5>
        <p>
            <form action="{{ url_for('upload.double_check') }}" method = "post">
                <input type="submit" name = "food_name" value="예측 음식">
            </form>
        </p>
    </div>
</body>
{% endblock %}
</html>

yp/templates/upload/upload_check2.html
{% extends "main.html" %}
{% block title %}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<body>
    <div style="text-align:center;">
        <div style="padding-bottom: 10px;">
            <img src = {{url_for("static", filename = photo)}}>
        </div>
        <div style="padding-bottom: 10px; margin: 0 auto;">
            <form action="{{ url_for('upload.how') }}" method = "post" style="padding-bottom: 10px; margin: 0 auto;">
                {% for food in food_list %}
                <input type="submit" value = "{{ food }}" name = "food_name">
                {% endfor %}
            </form>
            <form action="{{ url_for('upload.how') }}" method = "post">
                <input placeholder="직접 입력하기" name = "food_name">
                <button type="submit">제출</button>
            </form>
        </div>
    </div>
</body>
{% endblock %}
</html>

yp/templates/upload/upload_how.html
{% extends "main.html" %}
{% block title %}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<body>
    <div style="text-align:center;">
        <div style="padding-bottom: 20px;">
            <img src = {{url_for("static", filename = photo)}}>
        </div>
        <h5 style="padding-bottom: 10px;">음식을 어는 정도 드셨나요?</h5>
        <form action="{{ url_for('upload.result') }}" method = "post" style="padding-bottom: 10px; margin: 0 auto;">
            <p style="padding-bottom: 10px;">20% : <input type="submit" value = 0.2 name = "ratio"></p>
            <p style="padding-bottom: 10px;">40% : <input type="submit" value = 0.4 name = "ratio"></p>
            <p style="padding-bottom: 10px;">60% : <input type="submit" value = 0.6 name = "ratio"></p>
            <p style="padding-bottom: 10px;">80% : <input type="submit" value = 0.8 name = "ratio"></p>
            <p style="padding-bottom: 10px;">100% : <input type="submit" value = 1.0 name = "ratio"></p>
        </form>
    </div>
</body>
{% endblock %}
</html>

yp/templates/upload/upload_isnew.html
{% extends "main.html" %}
{% block title %}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<body>
    <div style="text-align: center;">
        <h5 style="padding-bottom: 10px;">Yam-Pick 데이터 베이스에 존재하지 않는 음식입니다.</h5>
        
        <p>
            <form action="{{ url_for('main.main') }}">
                <input type="submit" name = "food_name" value = "이동">
            </form>
        </p>
    </div>
</body>
{% endblock %}
</html>

yp/templates/upload/upload_result.html
{% extends "main.html" %}
{% block title %}{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
<body>
    <div >
        <h5 style="padding-bottom: 10px;">{{ text }}</h5>
        
        {% for res in res_list %}
        <div>
            {{res.food_name}}
        </div>
        {% endfor %}
    </div>
</body>
{% endblock %}
</html>